# Generated by Django 2.2.7 on 2019-12-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='personal/')),
                ('categories', models.CharField(choices=[('BS', 'Business cards'), ('Fl', 'Flyers'), ('LG', 'Logos'), ('IF', 'Infographics')], default='BS', max_length=200)),
            ],
        ),
    ]
